#!/bin/sh

# Make alias to get numbered list of directories in stack
alias dires="dirs -v"

# Alias to build hugo in dev directory
alias hugos="hugo server -wD -d dev"

# Make hugo server files to dev directory
alias gohugo="hugo server -D -d dev"

# firefox developer edition alias
alias firefox-dev="firefox-developer-edition"

# docker commands
alias docker-clean-unused='docker system prune --all --force --volumes'
alias docker-clean-all='docker stop $(docker container ls -a -q) && docker system prune -a -f --volumes'
alias dc="docker-compose"
alias dcrun="docker-compose run --rm"

# launch spt alias
alias spt="launchspt"
alias bt="bintest"

# get current term name
alias which_term="ps -aux | grep `ps -p $$ -o ppid=` | awk 'NR==1{print \$11}'"

#alias conda_activate='eval "$(~/miniconda3/bin/conda shell.zsh hook)"'

alias ls="exa"

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"


#### Voidrice Settings ####

# Verbosity and settings that you pretty much just always are going to want.
#alias \
#	cp="cp -iv" \
#	mv="mv -iv" \
#	rm="rm -vI" \
#	bc="bc -ql" \
#	mkd="mkdir -pv" \
#	yt="youtube-dl --add-metadata -i" \
#	yta="yt -x -f bestaudio/best" \
#	ffmpeg="ffmpeg -hide_banner"
#
## Colorize commands when possible.
#alias \
#	ls="ls -hN --color=auto --group-directories-first" \
#	grep="grep --color=auto" \
#	diff="diff --color=auto" \
#	ccat="highlight --out-format=ansi"
#
## These common commands are just too long! Abbreviate them.
#alias \
#	ka="killall" \
#	g="git" \
#	trem="transmission-remote" \
#	YT="youtube-viewer" \
#	sdn="sudo shutdown -h now" \
#	e="$EDITOR" \
#	v="$EDITOR" \
#	p="sudo pacman" \
#	xi="sudo xbps-install" \
#	xr="sudo xbps-remove -R" \
#	xq="xbps-query" \
#	z="zathura"
#
#alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
